# Generated by Django 4.1.7 on 2023-03-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pacientes',
            table='pacientes',
        ),
    ]
